In [150]:
import pandas as pd 
import numpy as np

In [151]:
def mse(y,f):
    mse = ((y - f)**2).mean(axis=0)
    return mse
def pearson(y,f):
    rp = np.corrcoef(y, f)[0,1]
    return rp

In [152]:
mix_deepsy = pd.read_csv("result_mix_data.csv")
blind_cell_deepsy = pd.read_csv("result_blind_cell.csv")
blind_drug_deepsy = pd.read_csv("result_blind_drug.csv")
mix_3omics = pd.read_csv("../../../model/save_model/GIN_ADD_AT/3omics/ge_mut_meth/mix_data/detail_result.csv")
test_dc = pd.read_csv("../../../data/split_data/mix_data/test_dc.csv")

In [153]:
mse(np.array(blind_cell_deepsy["synergy"]), np.array(blind_cell_deepsy["predict"]))

539.8357107084221

In [154]:
pd.options.display.max_rows = 999
mix_3omics

Drug1         Drug2 Cell line  Cosmic sample Id     synergy  \
0      VINORELBINE       MK-8776     LNCAP            907788    7.266235   
1          MK-8776   VINORELBINE     LNCAP            907788    7.266235   
2          MK-4827       MK-5108      OV90           1240197    8.382194   
3          MK-5108       MK-4827      OV90           1240197    8.382194   
4          BEZ-235   VINBLASTINE     LNCAP            907788   11.929272   
...            ...           ...       ...               ...         ...   
5885    BORTEZOMIB       MK-8776     SW837            909755 -194.361426   
5886  TEMOZOLOMIDE    PACLITAXEL  NCIH2122            722046 -237.581999   
5887    PACLITAXEL  TEMOZOLOMIDE  NCIH2122            722046 -237.581999   
5888    PACLITAXEL       BEZ-235  NCIH2122            722046 -281.436668   
5889       BEZ-235    PACLITAXEL  NCIH2122            722046 -281.436668   

                 Tissue  log_synergy    predict   abs_error   x_1_ats  \
0     urogenital_system     7.266235   7.267372    0.001136  0.081112   
1     urogenital_system     7.266235   7.267373    0.001138  0.918888   
2     urogenital_system     8.382195   8.383963    0.001768  0.752162   
3     urogenital_system     8.382195   8.383963    0.001768  0.247838   
4     urogenital_system    11.929272  11.945415    0.016143  0.744846   
...                 ...          ...        ...         ...       ...   
5885   digestive_system  -194.361420   6.969862  201.331280  0.317178   
5886               lung  -237.582000   3.820318  241.402310  0.994840   
5887               lung  -237.582000   3.820317  241.402310  0.005160   
5888               lung  -281.436680  11.730732  293.167420  0.048268   
5889               lung  -281.436680  11.730732  293.167420  0.951731   

       x_2_ats  
0     0.918888  
1     0.081112  
2     0.247838  
3     0.752162  
4     0.255154  
...        ...  
5885  0.682822  
5886  0.005160  
5887  0.994840  
5888  0.951732  
5889  0.048269  

[5890 rows x 11 columns]

In [155]:
pd.options.display.max_rows = 999
mix_deepsy[mix_deepsy["Drug1"]=="MK-8776"].sort_values(["Drug2", "Cell line"])

Drug1             Drug2 Cell line  Cosmic sample Id     synergy  \
1275  MK-8776              5-FU      A375            906793   22.611833   
1425  MK-8776              5-FU      A375            906793   22.611833   
3624  MK-8776              5-FU     HT144            907067    3.370729   
3864  MK-8776              5-FU     HT144            907067    3.370729   
262   MK-8776              5-FU    NCIH23            905942   -0.051990   
1100  MK-8776              5-FU    NCIH23            905942   -0.051990   
1167  MK-8776              5-FU  RPMI7951            910903    4.923621   
1876  MK-8776              5-FU  RPMI7951            910903    4.923621   
2480  MK-8776           ABT-888  NCIH2122            722046   -7.600735   
2563  MK-8776           ABT-888  NCIH2122            722046   -7.600735   
1767  MK-8776           ABT-888     OCUBM            909256   12.818050   
3048  MK-8776           ABT-888     OCUBM            909256   12.818050   
936   MK-8776           ABT-888    UACC62            905976    1.060457   
1779  MK-8776           ABT-888    UACC62            905976    1.060457   
2108  MK-8776           AZD1775      A375            906793   62.177991   
2251  MK-8776           AZD1775      A375            906793   62.177991   
312   MK-8776           AZD1775     HT144            907067   45.710186   
731   MK-8776           AZD1775     HT144            907067   45.710186   
3375  MK-8776           AZD1775     OCUBM            909256   65.904120   
3406  MK-8776           AZD1775     OCUBM            909256   65.904120   
3284  MK-8776           AZD1775  RPMI7951            910903   32.437258   
3527  MK-8776           AZD1775  RPMI7951            910903   32.437258   
3237  MK-8776           AZD1775   SKMEL30            909726   64.517117   
3493  MK-8776           AZD1775   SKMEL30            909726   64.517117   
3703  MK-8776           AZD1775    SKMES1            909728    4.100323   
3778  MK-8776           AZD1775    SKMES1            909728    4.100323   
4424  MK-8776           AZD1775      VCAP           1299075   78.225099   
4432  MK-8776           AZD1775      VCAP           1299075   78.225099   
4492  MK-8776           BEZ-235     HT144            907067 -140.365708   
4495  MK-8776           BEZ-235     HT144            907067 -140.365708   
476   MK-8776           BEZ-235      LOVO            907790   22.426613   
626   MK-8776           BEZ-235      LOVO            907790   22.426613   
3129  MK-8776           BEZ-235    NCIH23            905942   18.627360   
3433  MK-8776           BEZ-235    NCIH23            905942   18.627360   
2183  MK-8776           BEZ-235   NCIH520            908443   22.615648   
2195  MK-8776           BEZ-235   NCIH520            908443   22.615648   
18    MK-8776           BEZ-235     OCUBM            909256   22.780490   
283   MK-8776           BEZ-235     OCUBM            909256   22.780490   
3927  MK-8776           BEZ-235     T-47D            905945  103.966988   
4085  MK-8776           BEZ-235     T-47D            905945  103.966988   
3367  MK-8776        BORTEZOMIB      A375            906793    0.194229   
3729  MK-8776        BORTEZOMIB      A375            906793    0.194229   
4415  MK-8776        BORTEZOMIB     HT144            907067 -167.524733   
4450  MK-8776        BORTEZOMIB     HT144            907067 -167.524733   
5     MK-8776        BORTEZOMIB   SK-OV-3            905959  -16.169448   
1811  MK-8776        BORTEZOMIB   SK-OV-3            905959  -16.169448   
4345  MK-8776        BORTEZOMIB     T-47D            905945   -8.126399   
4390  MK-8776        BORTEZOMIB     T-47D            905945   -8.126399   
1436  MK-8776       CARBOPLATIN     HT144            907067   17.309614   
1862  MK-8776       CARBOPLATIN     HT144            907067   17.309614   
3293  MK-8776       CARBOPLATIN  NCIH1650            687800    0.121350   
3706  MK-8776       CARBOPLATIN  NCIH1650            687800    0.121350   
3242  MK-8776       CARBOPLATIN  

In [156]:
len(np.unique(test_dc["Drug1"]))

38

In [157]:
import torch
import torch.nn as nn

In [158]:
#batch, feature
torch.manual_seed(42)
xt = torch.Tensor([
    [0.12312, 0.123312, 0.534534],
    [0.12312, 0.123312, 0.534534],
    [0.12312, 0.123312, 0.534534],
])
x_1 = torch.randn(3,9)
x_2 = torch.stack([x_1[2,:], x_1[1, :], x_1[0,:]])
# print(x_1)
# print(x_2)
key_drug = nn.Linear(9, 9)
key_xt_op = nn.Linear(3, 3)
at_fc = nn.Linear((9*2+3), 1) #21 -> 1
leaky_relu = nn.LeakyReLU()

key_xt = key_xt_op(xt)
key_drug_1 = key_drug(x_1)
key_drug_2 = key_drug(x_2)

a_drug_1 = torch.exp(leaky_relu(at_fc(torch.cat((key_drug_1, key_xt, key_drug_2), 1))))
a_drug_2 = torch.exp(leaky_relu(at_fc(torch.cat((key_drug_2, key_xt, key_drug_1), 1))))
# a_drug_1 = (torch.cat((key_drug_1, key_xt, key_drug_2), 1)) #1x21
# a_drug_2 = (torch.cat((key_drug_2, key_xt, key_drug_1), 1))
total = a_drug_1+a_drug_2
a_drug_1 = torch.div(a_drug_1, total)
a_drug_2 = torch.div(a_drug_2, total)
x_1 = a_drug_1*x_1
x_2 = a_drug_2*x_2
x_drug_combine = x_1 + x_2

In [159]:
a_drug_1

tensor([[0.5002],
        [0.5000],
        [0.4998]], grad_fn=<DivBackward0>)

In [160]:
a_drug_2

tensor([[0.4998],
        [0.5000],
        [0.5002]], grad_fn=<DivBackward0>)

In [161]:
a_drug_1+a_drug_2

tensor([[1.],
        [1.],
        [1.]], grad_fn=<AddBackward0>)

In [162]:
pd.options.display.max_rows = 5
mix_3omics[mix_3omics["Drug1"] == "BEZ-235"].sort_values(["Drug2", "Cell line"])

Drug1    Drug2 Cell line  Cosmic sample Id   synergy Tissue  \
211   BEZ-235     5-FU     HT144            907067  2.323090   skin   
1412  BEZ-235     5-FU  NCIH2122            722046  7.697273   lung   
...       ...      ...       ...               ...       ...    ...   
1045  BEZ-235  ZOLINZA   SKMEL30            909726  9.722653   skin   
804   BEZ-235  ZOLINZA    UACC62            905976  8.805480   skin   

      log_synergy   predict  abs_error   x_1_ats   x_2_ats  
211      2.323090  2.971349   0.648259  0.066350  0.933650  
1412     7.697273  3.001459   4.695814  0.066350  0.933651  
...           ...       ...        ...       ...       ...  
1045     9.722652  6.303629   3.419023  0.134679  0.865321  
804      8.805480  6.210387   2.595093  0.134680  0.865320  

[206 rows x 11 columns]

In [163]:
mix_3omics[mix_3omics["Drug2"] == "BEZ-235"].sort_values(["Drug1", "Cell line"])

Drug1    Drug2 Cell line  Cosmic sample Id   synergy Tissue  \
210      5-FU  BEZ-235     HT144            907067  2.323090   skin   
1413     5-FU  BEZ-235  NCIH2122            722046  7.697273   lung   
...       ...      ...       ...               ...       ...    ...   
1044  ZOLINZA  BEZ-235   SKMEL30            909726  9.722653   skin   
805   ZOLINZA  BEZ-235    UACC62            905976  8.805480   skin   

      log_synergy   predict  abs_error   x_1_ats   x_2_ats  
210      2.323090  2.971349   0.648259  0.933651  0.066350  
1413     7.697273  3.001459   4.695815  0.933651  0.066349  
...           ...       ...        ...       ...       ...  
1044     9.722652  6.303630   3.419023  0.865320  0.134680  
805      8.805480  6.210387   2.595093  0.865320  0.134680  

[206 rows x 11 columns]